explicitly build .so file

diff --git a/c/Makefile b/c/Makefile
--- a/c/Makefile
+++ b/c/Makefile
@@ -1,10 +1,13 @@
 # CPL used c99 features, sorry.
-CFLAGS = -g -O2 --std=c99
+CFLAGS = -g -O2 --std=c99 -Wall
 
 all: test_image
 
-test_image: bee_mem_file.h test_image.o fpga.o
-	$(CC) $(CFLAGS) test_image.o fpga.o -o test_image
+test_image: bee_mem_file.h test_image.o libfpga.so
+	$(CC) $(CFLAGS) test_image.o -L. -lfpga -o test_image
+
+libfpga.so: fpga.c
+	$(CC) -shared -fPIC $(CFLAGS) $< -o $@
 
 # Probe for this machine's FPGA BAR0 access file.
 # Note that this _always_ probes.
@@ -13,7 +16,8 @@ bee_mem_file.h::
 	@( \
 	PROBED_FILENAME=`get_fpga_mmap_file.sh`; \
 	if test -z "$${PROBED_FILENAME}"; then \
-		echo "could not find FPGA on bus, using default or last probed value in bee_mem_file.h!" >&2 ; \
+		echo "could not find FPGA on bus, using default value!" >&2 ; \
+		cp bee_mem_file.h-in bee_mem_file.h ; \
 	else \
 	        ( echo "#define PROBED_FILENAME \"$${PROBED_FILENAME}\"" ; \
 	      	  cat bee_mem_file.h-in ;\
@@ -23,5 +27,5 @@ bee_mem_file.h::
 	)
 
 clean:
-	rm -f *.o *.S *.s *~
+	rm -f *.o *.so *.S *.s *~
 	rm -f test_image bee_mem_file.h
